export const mockWeatherData = {
  loading: false,
  error: false,
  currentWeather: {
    number: 1,
    name: "Today",
    startTime: "2024-10-05T10:00:00-05:00",
    endTime: "2024-10-05T18:00:00-05:00",
    isDaytime: true,
    temperature: 96,
    temperatureUnit: "F",
    temperatureTrend: "",
    probabilityOfPrecipitation: {
      unitCode: "wmoUnit:percent",
      value: null,
    },
    windSpeed: "15 to 25 mph",
    windDirection: "SW",
    icon: "https://api.weather.gov/icons/land/day/wind_skc?size=medium",
    shortForecast: "Sunny",
    detailedForecast:
      "Sunny, with a high near 96. Southwest wind 15 to 25 mph, with gusts as high as 35 mph.",
  },
  hourlyForcast: [
    {
      number: 1,
      name: "",
      startTime: "2024-10-05T10:00:00-05:00",
      endTime: "2024-10-05T11:00:00-05:00",
      isDaytime: true,
      temperature: 72,
      temperatureUnit: "F",
      temperatureTrend: "",
      probabilityOfPrecipitation: {
        unitCode: "wmoUnit:percent",
        value: 0,
      },
      dewpoint: {
        unitCode: "wmoUnit:degC",
        value: 12.777777777777779,
      },
      relativeHumidity: {
        unitCode: "wmoUnit:percent",
        value: 55,
      },
      windSpeed: "15 mph",
      windDirection: "S",
      icon: "https://api.weather.gov/icons/land/day/skc?size=small",
      shortForecast: "Sunny",
      detailedForecast: "",
    },
    {
      number: 2,
      name: "",
      startTime: "2024-10-05T11:00:00-05:00",
      endTime: "2024-10-05T12:00:00-05:00",
      isDaytime: true,
      temperature: 79,
      temperatureUnit: "F",
      temperatureTrend: "",
      probabilityOfPrecipitation: {
        unitCode: "wmoUnit:percent",
        value: 0,
      },
      dewpoint: {
        unitCode: "wmoUnit:degC",
        value: 12.777777777777779,
      },
      relativeHumidity: {
        unitCode: "wmoUnit:percent",
        value: 43,
      },
      windSpeed: "20 mph",
      windDirection: "SW",
      icon: "https://api.weather.gov/icons/land/day/skc?size=small",
      shortForecast: "Sunny",
      detailedForecast: "",
    },
    {
      number: 3,
      name: "",
      startTime: "2024-10-05T12:00:00-05:00",
      endTime: "2024-10-05T13:00:00-05:00",
      isDaytime: true,
      temperature: 86,
      temperatureUnit: "F",
      temperatureTrend: "",
      probabilityOfPrecipitation: {
        unitCode: "wmoUnit:percent",
        value: 0,
      },
      dewpoint: {
        unitCode: "wmoUnit:degC",
        value: 12.222222222222221,
      },
      relativeHumidity: {
        unitCode: "wmoUnit:percent",
        value: 34,
      },
      windSpeed: "25 mph",
      windDirection: "SW",
      icon: "https://api.weather.gov/icons/land/day/wind_skc?size=small",
      shortForecast: "Sunny",
      detailedForecast: "",
    },
    {
      number: 4,
      name: "",
      startTime: "2024-10-05T13:00:00-05:00",
      endTime: "2024-10-05T14:00:00-05:00",
      isDaytime: true,
      temperature: 91,
      temperatureUnit: "F",
      temperatureTrend: "",
      probabilityOfPrecipitation: {
        unitCode: "wmoUnit:percent",
        value: 0,
      },
      dewpoint: {
        unitCode: "wmoUnit:degC",
        value: 11.666666666666666,
      },
      relativeHumidity: {
        unitCode: "wmoUnit:percent",
        value: 28,
      },
      windSpeed: "25 mph",
      windDirection: "SW",
      icon: "https://api.weather.gov/icons/land/day/wind_skc?size=small",
      shortForecast: "Sunny",
      detailedForecast: "",
    },
    {
      number: 5,
      name: "",
      startTime: "2024-10-05T14:00:00-05:00",
      endTime: "2024-10-05T15:00:00-05:00",
      isDaytime: true,
      temperature: 93,
      temperatureUnit: "F",
      temperatureTrend: "",
      probabilityOfPrecipitation: {
        unitCode: "wmoUnit:percent",
        value: 0,
      },
      dewpoint: {
        unitCode: "wmoUnit:degC",
        value: 10.555555555555555,
      },
      relativeHumidity: {
        unitCode: "wmoUnit:percent",
        value: 24,
      },
      windSpeed: "25 mph",
      windDirection: "SW",
      icon: "https://api.weather.gov/icons/land/day/wind_skc?size=small",
      shortForecast: "Sunny",
      detailedForecast: "",
    },
    {
      number: 6,
      name: "",
      startTime: "2024-10-05T15:00:00-05:00",
      endTime: "2024-10-05T16:00:00-05:00",
      isDaytime: true,
      temperature: 95,
      temperatureUnit: "F",
      temperatureTrend: "",
      probabilityOfPrecipitation: {
        unitCode: "wmoUnit:percent",
        value: 1,
      },
      dewpoint: {
        unitCode: "wmoUnit:degC",
        value: 9.444444444444445,
      },
      relativeHumidity: {
        unitCode: "wmoUnit:percent",
        value: 21,
      },
      windSpeed: "25 mph",
      windDirection: "SW",
      icon: "https://api.weather.gov/icons/land/day/wind_skc?size=small",
      shortForecast: "Sunny",
      detailedForecast: "",
    },
    {
      number: 7,
      name: "",
      startTime: "2024-10-05T16:00:00-05:00",
      endTime: "2024-10-05T17:00:00-05:00",
      isDaytime: true,
      temperature: 96,
      temperatureUnit: "F",
      temperatureTrend: "",
      probabilityOfPrecipitation: {
        unitCode: "wmoUnit:percent",
        value: 2,
      },
      dewpoint: {
        unitCode: "wmoUnit:degC",
        value: 7.777777777777778,
      },
      relativeHumidity: {
        unitCode: "wmoUnit:percent",
        value: 18,
      },
      windSpeed: "25 mph",
      windDirection: "SW",
      icon: "https://api.weather.gov/icons/land/day/wind_skc?size=small",
      shortForecast: "Sunny",
      detailedForecast: "",
    },
    {
      number: 8,
      name: "",
      startTime: "2024-10-05T17:00:00-05:00",
      endTime: "2024-10-05T18:00:00-05:00",
      isDaytime: true,
      temperature: 94,
      temperatureUnit: "F",
      temperatureTrend: "",
      probabilityOfPrecipitation: {
        unitCode: "wmoUnit:percent",
        value: 2,
      },
      dewpoint: {
        unitCode: "wmoUnit:degC",
        value: 7.777777777777778,
      },
      relativeHumidity: {
        unitCode: "wmoUnit:percent",
        value: 19,
      },
      windSpeed: "15 mph",
      windDirection: "SW",
      icon: "https://api.weather.gov/icons/land/day/skc?size=small",
      shortForecast: "Sunny",
      detailedForecast: "",
    },
    {
      number: 9,
      name: "",
      startTime: "2024-10-05T18:00:00-05:00",
      endTime: "2024-10-05T19:00:00-05:00",
      isDaytime: false,
      temperature: 92,
      temperatureUnit: "F",
      temperatureTrend: "",
      probabilityOfPrecipitation: {
        unitCode: "wmoUnit:percent",
        value: 2,
      },
      dewpoint: {
        unitCode: "wmoUnit:degC",
        value: 7.222222222222222,
      },
      relativeHumidity: {
        unitCode: "wmoUnit:percent",
        value: 20,
      },
      windSpeed: "15 mph",
      windDirection: "NW",
      icon: "https://api.weather.gov/icons/land/night/skc?size=small",
      shortForecast: "Clear",
      detailedForecast: "",
    },
    {
      number: 10,
      name: "",
      startTime: "2024-10-05T19:00:00-05:00",
      endTime: "2024-10-05T20:00:00-05:00",
      isDaytime: false,
      temperature: 86,
      temperatureUnit: "F",
      temperatureTrend: "",
      probabilityOfPrecipitation: {
        unitCode: "wmoUnit:percent",
        value: 1,
      },
      dewpoint: {
        unitCode: "wmoUnit:degC",
        value: 6.111111111111111,
      },
      relativeHumidity: {
        unitCode: "wmoUnit:percent",
        value: 22,
      },
      windSpeed: "15 mph",
      windDirection: "N",
      icon: "https://api.weather.gov/icons/land/night/skc?size=small",
      shortForecast: "Clear",
      detailedForecast: "",
    },
    {
      number: 11,
      name: "",
      startTime: "2024-10-05T20:00:00-05:00",
      endTime: "2024-10-05T21:00:00-05:00",
      isDaytime: false,
      temperature: 77,
      temperatureUnit: "F",
      temperatureTrend: "",
      probabilityOfPrecipitation: {
        unitCode: "wmoUnit:percent",
        value: 1,
      },
      dewpoint: {
        unitCode: "wmoUnit:degC",
        value: 5,
      },
      relativeHumidity: {
        unitCode: "wmoUnit:percent",
        value: 28,
      },
      windSpeed: "15 mph",
      windDirection: "N",
      icon: "https://api.weather.gov/icons/land/night/skc?size=small",
      shortForecast: "Clear",
      detailedForecast: "",
    },
    {
      number: 12,
      name: "",
      startTime: "2024-10-05T21:00:00-05:00",
      endTime: "2024-10-05T22:00:00-05:00",
      isDaytime: false,
      temperature: 72,
      temperatureUnit: "F",
      temperatureTrend: "",
      probabilityOfPrecipitation: {
        unitCode: "wmoUnit:percent",
        value: 1,
      },
      dewpoint: {
        unitCode: "wmoUnit:degC",
        value: 2.7777777777777777,
      },
      relativeHumidity: {
        unitCode: "wmoUnit:percent",
        value: 28,
      },
      windSpeed: "10 mph",
      windDirection: "N",
      icon: "https://api.weather.gov/icons/land/night/skc?size=small",
      shortForecast: "Clear",
      detailedForecast: "",
    },
    {
      number: 13,
      name: "",
      startTime: "2024-10-05T22:00:00-05:00",
      endTime: "2024-10-05T23:00:00-05:00",
      isDaytime: false,
      temperature: 69,
      temperatureUnit: "F",
      temperatureTrend: "",
      probabilityOfPrecipitation: {
        unitCode: "wmoUnit:percent",
        value: 0,
      },
      dewpoint: {
        unitCode: "wmoUnit:degC",
        value: 1.6666666666666667,
      },
      relativeHumidity: {
        unitCode: "wmoUnit:percent",
        value: 29,
      },
      windSpeed: "10 mph",
      windDirection: "N",
      icon: "https://api.weather.gov/icons/land/night/skc?size=small",
      shortForecast: "Clear",
      detailedForecast: "",
    },
  ],
  dateOptions: [
    {
      label: "10/5/2024",
      value: "10/5/2024",
    },
    {
      label: "10/6/2024",
      value: "10/6/2024",
    },
    {
      label: "10/7/2024",
      value: "10/7/2024",
    },
    {
      label: "10/8/2024",
      value: "10/8/2024",
    },
    {
      label: "10/9/2024",
      value: "10/9/2024",
    },
    {
      label: "10/10/2024",
      value: "10/10/2024",
    },
    {
      label: "10/11/2024",
      value: "10/11/2024",
    },
  ],
};
